# Generated by Django 4.2.1 on 2023-05-26 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productURL', models.URLField()),
                ('imageURL', models.URLField()),
                ('name', models.TextField()),
                ('price', models.FloatField()),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
