# Generated by Django 4.2.1 on 2023-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketpriceAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='searched_products',
            field=models.ManyToManyField(to='marketpriceAPI.product'),
        ),
    ]
