# Generated by Django 4.2.1 on 2023-07-11 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketpriceAPI', '0002_user_searched_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='searched_products',
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacting_item', to='marketpriceAPI.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interacting_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-interaction_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('user', 'product'), name='unique_interaction'),
        ),
    ]
